FROM multiarch/debian-debootstrap:amd64-stretch-slim

RUN apt-get update \
 && apt-get install --no-install-recommends -y -q ca-certificates openssl wget unbound

WORKDIR /etc/unbound
RUN wget -O root.hints https://www.internic.net/domain/named.root

RUN mkdir /scripts
ADD unbound.sh /scripts/unbound.sh
RUN chmod +x /scripts/unbound.sh

ENTRYPOINT ["/scripts/unbound.sh"]